INSERT INTO cigarette_cigarette
(name, brand, price, amount) VALUES
("Capri", "Souza Cruz S/A", 3.0, 20),
("Charm", "Souza Cruz S/A", 7.0, 20),
("Derby Azul", "Souza Cruz S/A", 4.24, 20),
("Derby Prata", "Souza Cruz S/A", 4.24, 20),
("Derby Vermelho", "Souza Cruz S/A", 4.24, 20),
("Dunhill Blue", "Souza Cruz S/A", 5.50, 20),
("Dunhill Crema", "Souza Cruz S/A", 5.50, 20),
("Dunhill Calton Blend", "Souza Cruz S/A", 5.50, 20),
("Free Blue", "Souza Cruz S/A", 4.75, 20),
("Free Red", "Souza Cruz S/A", 5.25, 20),
("Hilton", "Souza Cruz S/A", 4.30, 20),
("Hollywood Red", "Souza Cruz S/A", 4.50, 20),
("Hollywood Blue", "Souza Cruz S/A", 4.50, 20),
("Hollywood Caribe", "Souza Cruz S/A", 4.50, 20),
("Lucky Strike Brue", "Souza Cruz S/A", 5.00, 20),
("Lucky Strike CLICK & ROLL", "Souza Cruz S/A", 5.25, 20),
("Lucky Strike Original", "Souza Cruz S/A", 5.00, 20),
("Plaza Gold", "Souza Cruz S/A", 4.30, 20),
("Plaza Red", "Souza Cruz S/A", 4.30, 20),
("Plaza Ritz", "Souza Cruz S/A", 4.30, 20);